# Generated by Django 3.2 on 2022-11-30 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_pw', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 30, 11, 3, 27, 342552, tzinfo=utc))),
            ],
        ),
    ]
