# Generated by Django 3.2 on 2022-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
